### ISSUE TITLE
High TTFB

### ISSUE THREAD

**Issue by blhi-jed** [livewire-ui/modal#75] opened 2021-08-03 09:05 UTC
On a fresh laravel app, response is fine. 

However, after adding this to a tailwind-themed app, my TimeToFirstByte is above 2seconds.
I tried to just make a basic modal, no model-queries, just plain.
I'm currently using Laravel 8 with custom theme using TailwindCSS + JIT.
Not sure how to debug the network-transfer part, but chrome dev-tools only points to 
laravel-ui-modal
Duration4.67 s (4.67 s network transfer + 0.47 ms resource loading)

<img width="1493" alt="Screen Shot 2021-08-03 at 1 02 49 PM" src="https://user-images.githubusercontent.com/35447270/127988973-18f3006e-a1cf-411d-b0e1-19eca9fadfcf.png">

So once the open-modal link is clicked, it takes at least 4 seconds before it actually shows.
I could be doing something wrong but not sure how to determine more and address this.
Also, apologies if this is not the right place to write this, and point me to the appropriate channel. Thanks

**Comment by PhiloNL** [comment] 2021-08-03 14:08
Hi @blhi-jed 
I would recommend installing something like [Clockwork](https://github.com/itsgoingd/clockwork) to figure out what is going on under the hood and see what is causing the latency issue. Given it works fine with a fresh Laravel installation, the issue must be created by a different third-party package.

**Comment by blhi-jed** [comment] 2021-08-04 04:25
I was thinking maybe if there where multiple components setup for the modal in once instance of a page, like in a loop, or on any part of the page, e.g. a modal in the header, or somewhere else, but ok i will investigate and let you know. Thanks for the clockwork link, my first time to see this, will report back.

**Comment by PhiloNL** [comment] 2021-08-05 11:41
Closing this issue, for now, let me know if the cause is related to this package.

**Closed** 2021-08-05 11:41 UTC

**Comment by blhi-jed** [comment] 2021-08-20 09:38
hi @PhiloNL i found the cause, and it was the blade-icons package not being cached. This is irrelevant to your package. 
I didn't notice that blade-icons had a caching function.
Livewire-UI modal is awesome. Thank you.

**Comment by PhiloNL** [comment] 2021-08-20 09:45
Hi @blhi-jed glad you found the issue. I'm happy to hear you like the Livewire UI modal 😄
