### ISSUE TITLE
Does not recognize methods when i call modal in the top of livewire component

### ISSUE THREAD

**Issue by AkramZerarka** [livewire-ui/modal#15] opened 2021-04-22 06:03 UTC

**Comment by AkramZerarka** [comment] 2021-04-22 06:03
<div class="grid justify-start grid-flow-col gap-2 mb-4 sm:auto-cols-max sm:justify-end" wire:ignore>
    <button class="text-white bg-blue-500 btn hover:bg-blue-600" wire:click="$emit('openModal', 'plans.create')">
        <x-heroicon-o-plus-sm class="h-5"/>
        <span class="hidden ml-2 xs:block">{{ __('Add plan') }}</span>
    </button>
</div>
<div class="bg-white border border-gray-200 rounded-sm shadow-lg">
    <header class="px-5 py-4">
        <h2 class="font-semibold text-gray-800">{{ __('All plans') }}<span class="px-2 font-medium text-gray-400">{{ count($plans) }}</span></h2>
    </header>
    <div>
        <div class="overflow-x-auto">
            <table class="w-full table-auto">
                <thead class="text-xs font-semibold text-gray-500 uppercase border-t border-b border-gray-200 bg-gray-50">
                    <tr>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold text-left">{{ __('Name') }}</div>
                        </th>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold text-left">{{ __('Amount') }}</div>
                        </th>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold text-left">{{ __('Currency') }}</div>
                        </th>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold text-left">{{ __('Description') }}</div>
                        </th>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold">{{ __('Action Status') }}</div>
                        </th>
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold">{{ __('Actions') }}</div>
                        </th>
                    </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-200">
                    @foreach ($plans as $plan => $value)
                    <tr>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="font-medium text-gray-800 capitalize">
                                    {{ $value['name'] }}
                                </div>
                            </div>
                        </td>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="text-left">
                                {{ number_format(floatval($value['amount']) /100,2,',','') }}
                            </div>
                        </td>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="text-left uppercase">
                                {{ $value['currency'] }}
                            </div>
                        </td>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="text-left uppercase">
                                {{ $value['description'] }}
                            </div>
                        </td>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <a wire:click='delete' class="flex justify-center">
                                @if ($value['active'] == 1)
                                <x-heroicon-o-eye class="h-5 text-green-500"/>
                                @else
                                <x-heroicon-o-eye-off class="h-5 text-red-500"/>
                                @endif
                            </a>
                        </td>
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="text-center">
                                <button onclick='Livewire.emit("openModal", "plans.delete", @json(["planid" => "$value[id]"]))'>
                                    <x-heroicon-o-trash class="h-5 text-red-500"/>
                                </button>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

**Comment by AkramZerarka** [comment] 2021-04-22 06:03
[](url)

**Comment by PhiloNL** [comment] 2021-04-22 14:05
I need more information and code samples, otherwise, I have no idea how to help.

**Comment by AkramZerarka** [comment] 2021-04-22 21:34
Hello sir 
for exemple when i call the method to open the modal in the top of my livewire component and do some other methods under the first call, all the methods are ignored 
for exemple 
```
<button class="text-white bg-blue-500 btn hover:bg-blue-600" wire:click="$emit('openModal', 'plans.create')">
        <x-heroicon-o-plus-sm class="h-5"/>
        <span class="hidden ml-2 xs:block">{{ __('Add plan') }}</span>
</button>

<div class="bg-white border border-gray-200 rounded-sm shadow-lg">
    <header class="px-5 py-4">
        <h2 class="font-semibold text-gray-800">{{ __('All plans') }}<span class="px-2 font-medium text-gray-400">{{ count($plans) }}</span></h2>
    </header>
    <div>
        <div class="overflow-x-auto">
            <table class="w-full table-auto">
                <thead class="text-xs font-semibold text-gray-500 uppercase border-t border-b border-gray-200 bg-gray-50">
                    <tr>
                        ....
                        <th class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <div class="font-semibold">{{ __('Action Status') }}</div>
                        </th>
                        ....
                    </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-200">
                    @foreach ($plans as $plan => $value)
                    <tr wire:key="{{ $value['id'] }}">
                        ...
                        <td class="px-2 py-3 first:pl-5 last:pr-5 whitespace-nowrap">
                            <a wire:click='delete' class="flex justify-center">
                                @if ($value['active'] == 1)
                                <x-heroicon-o-eye class="h-5 text-green-500"/>
                                @else
                                <x-heroicon-o-eye-off class="h-5 text-red-500"/>
                                @endif
                            </a>
                        </td>
                        ...
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

```
for exemple method delete doen't work 
thank you

**Comment by PhiloNL** [comment] 2021-04-23 19:24
Thanks for posting some more information. Unfortunately, it's still difficult for me to assess what the problem is. If you could create a Github repository with demo-code and step-by-step instructions on what you are doing and what is not working I'm able to help you.

**Comment by PhiloNL** [comment] 2021-04-26 13:10
Closing for now, let me know if this is still an issue.

**Closed** 2021-04-26 13:10 UTC
