### ISSUE TITLE
LivewireUiModal is not defined

### ISSUE THREAD

**Issue by Elshaden** [livewire-ui/modal#7] opened 2021-04-09 17:49 UTC
Hi

I installed the package as instructed, but get this error in console
```
Uncaught ReferenceError: LivewireUiModal is not defined
    at eval (eval at tryCatch.el.el (app.js:152), <anonymous>:3:36)
    at tryCatch.el.el (app.js:152)
    at tryCatch (app.js:139)
    at saferEval (app.js:147)
    at new Component (app.js:1469)
    at Object.initializeComponent (app.js:1919)
    at app.js:1864
    at app.js:1878
    at NodeList.forEach (<anonymous>)
    at Object.discoverComponents (app.js:1877)
```
 any way to fix this?

**Comment by PhiloNL** [comment] 2021-04-10 22:34
Hi there! Just double checking, did you include all directives?

```
@livewire('livewire-ui-modal')
@livewireUIScripts
@livewireScripts

```

And did you publish the scripts?

`php artisan vendor:publish --tag=livewire-ui:public`

**Comment by PhiloNL** [comment] 2021-04-12 12:18
Closing this issue. If it's still a problem, let me know. Thanks!

**Closed by PhiloNL** 2021-04-12 12:18 UTC

**Comment by amit-viacon** [comment] 2021-08-10 11:54
Getting the same error

**Comment by amit-viacon** [comment] 2021-08-11 06:36
Found the cause

Config file is having
```php
'include_js' => false
```

Change to

```php
'include_js' => true
```
